services:
  _defaults:
    autowire: true
    autoconfigure: true

  WechatOfficialAccountDraftBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags:
      - { name: doctrine.fixture.orm }